config/routes.rb
Jerrymagazine::Application.routes.draw do
  
  mount AssetServer.instance => '/assets'

  match '/admin' => 'admin#index', :as => :admin
  match '/admin/editions/:action' => 'editions_admin', :as => :editions_admin
  match '/admin/works/:action' => 'works_admin', :as => :works_admin
  match '/admin/links/:action' => 'links_admin', :as => :links_admin
  match '/admin/users/:action' => 'users', :as => :users_admin
  
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  
  resources :users
  resource :session
  
  match '/about_us' => 'public#about_us', :as => :about_us
  match '/note_to_note' => 'public#editors_letter', :as => :editors_letter
  match '/submit' => 'public#submit', :as => :submit_page
  match '/home' => 'public#index'
  match '/archives/:action' => 'editions', :as => :archives

  resources :links
  match '/friends-and-bastards' => 'links#index', :as => :friends_and_bastards
  match '/works/:id/:page'  => 'works#show', :as => :work_page
  resources :works
  resources :editions
  resources :contributors

  root :to => "public#front_cover"

end

app/models/edition.rb
class Edition < ActiveRecord::Base
  belongs_to  :user
  has_many    :works
  has_many    :contributors, :through => :works, :order => 'lastname', :uniq => true
  
  validates :title, :presence => true
  validates :edition_no, :numericality => true
  
  has_friendly_id :title, :use_slug => true
  
  def contributors_content_calc
    return textilize(contributors_content).html_safe unless contributors_content.blank?
  end
  
  def description_calc
    return textilize(description).html_safe
  end
  
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  
  
  # GET /editions
  # GET /editions.xml
  def index
    @editions = Edition.find_all_by_published(true, :order => "publish_date DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @editions }
    end
  end

  # GET /editions/1
  # GET /editions/1.xml
  def show
    @edition  = Edition.find(params[:id])
    session[:edition_id]  = @edition.id
    expire_site_pages
    redirect_to home_path
  end
  
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/views/editions/index.html.erb
<h2>Editions</h2>

<table>
<% @editions.each do |edition| %>
  <tr>
    <td><%= link_to edition.title, edition %></td>
  </tr>
<% end %>
</table>

app/views/editions/show.html.erb
<p>
  <b>Title:</b>
  <%= @edition.title %>
</p>

<p>
  <b>Edition no:</b>
  <%= @edition.edition_no %>
</p>

<p>
  <b>Publish date:</b>
  <%= @edition.publish_date %>
</p>

<p>
  <b>Description:</b>
  <%= @edition.description %>
</p>

<%= link_to 'Back', editions_path %>

<h2>Edition works</h2>

<table>
  <tr>
    <th>Type</th>
    <th>Title</th>
    <th>Abstract</th>
    <th>Work content</th>
    <th>User</th>
  </tr>

<% @edition.works.each do |work| %>
  <tr>
    <td><%= work.work_type %></td>
    <td><%= work.title_calc %></td>
    <td><%=truncate(work.abstract_calc) %></td>
    <td><%=truncate(work.work_content_calc) %></td>
    <td><%= work.user.get_fullname %></td>
    <td><%= link_to 'Show', work %></td>
  </tr>
<% end %>
</table>