config/routes.rb
Jerrymagazine::Application.routes.draw do
  
  mount AssetServer.instance => '/assets'

  match '/admin' => 'admin#index', :as => :admin
  match '/admin/editions/:action' => 'editions_admin', :as => :editions_admin
  match '/admin/works/:action' => 'works_admin', :as => :works_admin
  match '/admin/links/:action' => 'links_admin', :as => :links_admin
  match '/admin/users/:action' => 'users', :as => :users_admin
  
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  
  resources :users
  resource :session
  
  match '/about_us' => 'public#about_us', :as => :about_us
  match '/note_to_note' => 'public#editors_letter', :as => :editors_letter
  match '/submit' => 'public#submit', :as => :submit_page
  match '/home' => 'public#index'
  match '/archives/:action' => 'editions', :as => :archives

  resources :links
  match '/friends-and-bastards' => 'links#index', :as => :friends_and_bastards
  match '/works/:id/:page'  => 'works#show', :as => :work_page
  resources :works
  resources :editions
  resources :contributors

  root :to => "public#front_cover"

end

app/models/work.rb
class Work < ActiveRecord::Base
  
  has_attached_file :attachment1, 
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",
    :bucket => 'jerry-1pzrp75tx2ttjd1a7d02',
    :path => ":attachment/:id/:style/:filename"
    
  belongs_to  :edition
  belongs_to  :user
  belongs_to  :contributor, :class_name => 'User', :foreign_key => :user_id
  has_many    :work_pages, :dependent => :destroy
  accepts_nested_attributes_for :work_pages, :allow_destroy => true, :reject_if => proc { |attributes| attributes['page_number'].blank? }
  
  
  validates :title, :presence => true
  validates :title_tt, :presence => true
  validates :work_type, :presence => true
  
  has_friendly_id :title, :use_slug => true
  
  default_scope includes(:user, :edition)
  
  ###
  # INSTANCE METHODS
  #
  
  def title_calc
    if title_tt.blank?
      return white_list(title).html_safe
    else
      return textilize(title_tt).gsub!(/<p>|<\/p>/, "").html_safe
    end
  end
  
  def epigraph_calc
    if epigraph_tt.blank?
      return white_list(epigraph).html_safe
    else
      return textilize(epigraph_tt).html_safe
    end
  end
  
  def abstract_calc
    if abstract_tt.blank?
      return white_list(abstract).html_safe
    else
      return textilize(abstract_tt).html_safe
    end
  end
  
  def work_content_calc
    if work_content_tt.blank?
      return white_list(work_content).html_safe
    else
      return textilize(work_content_tt).html_safe
    end
  end
  
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  
  caches_page :show
  
  # GET /works
  # GET /works.xml
  def index
    @works = Work.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @works }
    end
  end

  # GET /works/1
  # GET /works/1.xml
  def show
    @work     = Work.find(params[:id])
    @edition  = @work.edition
    @page     = params[:page].blank? ? 1 : params[:page].to_i
    
    if !@work.work_pages.none?
      @work_page  = @work.work_pages[@page-1]
    end
    
    respond_to do |format|
      format.html { render :layout => 'work' }
      format.xml  { render :xml => @work }
    end
  end

end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_multi_page.haml
- if @work_page.work_image_file_name
  - if @work.images_lightbox
    .lightbox_info click images to open
    - @work.work_pages.each do |work_page|
      = link_to(image_tag(work_page.work_image.url), work_page.work_image.url, :rel => "work_lightbox", :class => "work_lightbox_image")
  - else
    = image_tag @work_page.work_image.url, :class => "work_image"
- else
  .main_work= @work_page.page_content_calc

app/views/works/_single_page.haml
- if @work.attachment1_file_name
  - if @work.images_lightbox
    .lightbox_info click image to open
    = link_to(image_tag(@work.attachment1.url), @work.attachment1.url, :rel => "work_lightbox", :class => "work_lightbox_image")
  - else
    = image_tag @work.attachment1.url, :class => "work_image"
- else
  .main_work= @work.work_content_calc

app/views/works/index.html.erb
<h1>Listing works</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Title</th>
    <th>Abstract</th>
    <th>Work content</th>
    <th>Edition</th>
    <th>Writer</th>
  </tr>

<% @works.each do |work| %>
  <tr>
    <td><%=h work.work_type %></td>
    <td><%=h work.title %></td>
    <td><%=truncate(h(work.abstract)) %></td>
    <td><%=truncate(h(work.work_content)) %></td>
    <td><%=h work.edition.edition_no.to_s%>: <%=h work.edition.title %></td>
    <td><%=h work.user.get_fullname %></td>
    <td><%= link_to 'Show', work %></td>
  </tr>
<% end %>
</table>

app/views/works/show.haml
- if @page == 1 || !@page
  %h3= @work.title_calc
  - if !@work.epigraph.blank?
    %p.epigraph= @work.epigraph_calc
  %p.name= @work.user.get_fullname
- if !@work.work_pages.none? && !@work.images_lightbox
  #work_links_top.work_links
    .page_links
      - @work.work_pages.each_with_index do |work_page, index|
        = link_to index+1, work_page_path(@work, :page => index+1), :class => "page_link #{if index+1 == @page then 'this_page' end}"
- if @work.work_pages.none?
  = render 'works/single_page'
- else
  = render 'works/multi_page'
#work_links_bottom.work_links
  = link_to 'Back', home_path, :class => "back_link"
  - if !@work.work_pages.none? && !@work.images_lightbox
    .page_links
      - @work.work_pages.each_with_index do |work_page, index|
        = link_to index+1, work_page_path(@work, :page => index+1), :class => "page_link #{if index+1 == @page then 'this_page' end}"