config/routes.rb
Jerrymagazine::Application.routes.draw do
  
  mount AssetServer.instance => '/assets'

  match '/admin' => 'admin#index', :as => :admin
  match '/admin/editions/:action' => 'editions_admin', :as => :editions_admin
  match '/admin/works/:action' => 'works_admin', :as => :works_admin
  match '/admin/links/:action' => 'links_admin', :as => :links_admin
  match '/admin/users/:action' => 'users', :as => :users_admin
  
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  
  resources :users
  resource :session
  
  match '/about_us' => 'public#about_us', :as => :about_us
  match '/note_to_note' => 'public#editors_letter', :as => :editors_letter
  match '/submit' => 'public#submit', :as => :submit_page
  match '/home' => 'public#index'
  match '/archives/:action' => 'editions', :as => :archives

  resources :links
  match '/friends-and-bastards' => 'links#index', :as => :friends_and_bastards
  match '/works/:id/:page'  => 'works#show', :as => :work_page
  resources :works
  resources :editions
  resources :contributors

  root :to => "public#front_cover"

end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  include Authentication
  include Authentication::ByPassword
  include Authentication::ByCookieToken
  
  has_many :works
  default_scope order('lastname, firstname')
  
  has_friendly_id :lastname, :use_slug => true

  #validates_presence_of     :login
  validates_length_of       :login,    :within => 3..40, :allow_blank => true
  validates_uniqueness_of   :login, :allow_blank => true
  validates_format_of       :login,    :with => Authentication.login_regex, :message => Authentication.bad_login_message, :allow_blank => true

  validates_presence_of     :firstname
  validates_format_of       :firstname,     :with => Authentication.name_regex,  :message => Authentication.bad_name_message, :allow_nil => true
  validates_length_of       :firstname,     :maximum => 100
  
  validates_presence_of     :lastname
  validates_format_of       :lastname,     :with => Authentication.name_regex,  :message => Authentication.bad_name_message, :allow_nil => true
  validates_length_of       :lastname,     :maximum => 100

  #validates_presence_of     :email
  validates_length_of       :email,    :within => 6..100, :allow_blank => true #r@a.wk
  validates_uniqueness_of   :email, :allow_blank => true
  validates_format_of       :email,    :with => Authentication.email_regex, :message => Authentication.bad_email_message, :allow_blank => true

  

  # HACK HACK HACK -- how to do attr_accessible from here?
  # prevents a user from submitting a crafted form that bypasses activation
  # anything else you want your user to change should be added here.
  #attr_accessible :login, :email, :lastname, :firstname, :group, :password, :password_confirmation, :writer_type, :bio



  # Authenticates a user by their login name and unencrypted password.  Returns the user or nil.
  #
  # uff.  this is really an authorization, not authentication routine.  
  # We really need a Dispatch Chain here or something.
  # This will also let us return a human error message.
  #
  def self.authenticate(login, password)
    return nil if login.blank? || password.blank?
    u = find_by_login(login.downcase) # need to get the salt
    u && u.authenticated?(password) ? u : nil
  end

  def login=(value)
    write_attribute :login, (value ? value.downcase : nil)
  end

  def email=(value)
    write_attribute :email, (value ? value.downcase : nil)
  end
  
  def get_fullname
    return "#{firstname} #{lastname}"
  end
  
  def get_edition_works(edition_id, work_type = nil)
    if work_type.blank?
      works.where(:edition_id => edition_id).order(:ordinal).all
    else
      works.where(:edition_id => edition_id, :work_type => work_type).order(:ordinal).all
    end
  end
  
  def tagline_calc
    return textilize(tagline).gsub!(/<p>|<\/p>/, "").html_safe unless tagline.blank?
  end
  
  def bio_calc
    if bio_tt.blank?
      return white_list(bio).html_safe
    else
      return textilize(bio_tt).html_safe
    end
  end
  
  protected
    


end

app/controllers/users_controller.rb
class UsersController < AdminController
  
  def index
    @users  = User.all :order => 'lastname'
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  # render new.rhtml
  def new
    @user = User.new
  end
 
  def create
    #logout_keeping_session!
    @user = User.new(params[:user])
    success = @user && @user.save
    if success && @user.errors.empty?
      # Protects against session fixation attacks, causes request forgery
      # protection if visitor resubmits an earlier form using back
      # button. Uncomment if you understand the tradeoffs.
      # reset session
      #self.current_user = @user # !! only do this is sign up!
      redirect_to :action => 'index'
      flash[:notice] = "New user signed up."
    else
      flash[:error]  = "New user not sigend up"
      render :action => 'new'
    end
  end
  
  # GET /admin/users/1/edit
  def edit
    @user = User.find(params[:id])
  end
  
  # PUT /admin/users/1
  # PUT /admin/users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        flash[:notice] = 'User was successfully updated.'
        format.html { redirect_to :action  => 'show', :id => @user }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to :action  => 'index' }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), user_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag = options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

app/views/users/_form.html.erb
<%= f.error_messages %>

<%= f.input :login %>

<%= f.input :email %>

<%= f.input :firstname %>

<%= f.input :lastname %>

<%= f.input :group,:collection => @user_group_opts %>

<%= f.input :password %>

<%= f.input :password_confirmation %>

<%= f.input :tagline %>

<%= f.input :bio_tt, :label => 'Bio' %>

<div>
  <p class="old_input_label">Click to <span>show</span> Bio (old version)</p>
  <div class="old_input">
    <%= f.input :bio, :label => 'Bio (old version)', :input_html => {:class => "mceEditor"} %>
  </div>
</div>

<%= f.button :submit %>

app/views/users/_user_bar.html.erb
<% if logged_in? -%>
  <div id="user-bar-greeting">Logged in as <%= link_to_current_user :content_method => :login %></div>
  <div id="user-bar-action"  >(<%= link_to "Log out", logout_path, { :title => "Log out" }    %>)</div>
<% else -%>
  <div id="user-bar-greeting"><%= link_to_login_with_IP 'Not logged in', :style => 'border: none;' %></div>
  <div id="user-bar-action"  ><%= link_to "Log in",  login_path,  { :title => "Log in" } %> /
                               <%= link_to "Sign up", signup_path, { :title => "Create an account" } %></div>
<% end -%>

app/views/users/edit.html.erb
<h2>Editing user</h2>

<%= simple_form_for @user, :url => {:action => 'update', :id => @user} do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

<%= link_to 'Show', users_admin_path(:id=> @user, :action => 'show'), :class => "button" %>
<%= link_to 'Back', users_admin_path, :class => "button" %>

app/views/users/index.html.erb
<h2>All Users</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Group</th>
    <th>Writer Type</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%=h user.get_fullname %></td>
    <td><%=h user.group %></td>
    <td><%=h user.writer_type %></td>
    <td><%= link_to 'Show', users_admin_path(:id=> user, :action => 'show'), :class => "button" %></td>
    <td><%= link_to 'Edit', users_admin_path(:id=> user, :action => 'edit'), :class => "button" %></td>
    <td><%= link_to 'Destroy', users_admin_path(:id=> user, :action => 'destroy'), :confirm => 'Are you sure?', :method => :delete, :class => "button negative" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New user', users_admin_path(:action => 'new'), :class => "button" %>

app/views/users/new.html.erb
<h2>Sign up as a new user</h2>
<% @user.password = @user.password_confirmation = nil %>

<%= simple_form_for @user, :url => users_path do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

app/views/users/show.html.erb
<h2>User Preview</h2>
<div id="preview_show">
  <div class="show_inline">
    <h4>First Name:</h4>
    <%= @user.firstname %>
  </div>
  <div class="show_inline">
    <h4>Last Name:</h4>
    <%= @user.lastname %>
  </div>
  <div class="show_inline">
    <h4>Group:</h4>
    <%= @user.group %>
  </div>
  <div class="show_inline">
    <h4>Writer Type:</h4>
    <%= @user.writer_type %>
  </div>

  <div class="show_inline">
    <h4>Tagline:</h4>
    <%= @user.tagline %>
  </div>
  
  <h4 class="cb">Bio:</h4>
  <%= @user.bio_calc %>


  <br class="cb"/>

  <%= link_to 'Edit', users_admin_path(:id=> @user, :action => 'edit'), :class => "button" %>
  <%= link_to 'Back', users_admin_path, :class => "button" %>

</div>