config/routes.rb
Jerrymagazine::Application.routes.draw do
  
  mount AssetServer.instance => '/assets'

  match '/admin' => 'admin#index', :as => :admin
  match '/admin/editions/:action' => 'editions_admin', :as => :editions_admin
  match '/admin/works/:action' => 'works_admin', :as => :works_admin
  match '/admin/links/:action' => 'links_admin', :as => :links_admin
  match '/admin/users/:action' => 'users', :as => :users_admin
  
  match '/logout' => 'sessions#destroy', :as => :logout
  match '/login' => 'sessions#new', :as => :login
  match '/register' => 'users#create', :as => :register
  match '/signup' => 'users#new', :as => :signup
  
  resources :users
  resource :session
  
  match '/about_us' => 'public#about_us', :as => :about_us
  match '/note_to_note' => 'public#editors_letter', :as => :editors_letter
  match '/submit' => 'public#submit', :as => :submit_page
  match '/home' => 'public#index'
  match '/archives/:action' => 'editions', :as => :archives

  resources :links
  match '/friends-and-bastards' => 'links#index', :as => :friends_and_bastards
  match '/works/:id/:page'  => 'works#show', :as => :work_page
  resources :works
  resources :editions
  resources :contributors

  root :to => "public#front_cover"

end

app/views/layouts/_footer.haml
%p
  &copy; Jerry Magazine #{Date.today.year}

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24875630-1']);
  _gaq.push(['_setDomainName', '.jerrymagazine.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/_main_mav.haml
%ul
  %li #{link_to('Home', home_path)}
  %li #{link_to('About', about_us_path)}
  %li #{link_to('Writers', contributors_path)}
  %li #{link_to('Past Issues', archives_path)}
  %li #{link_to('Submit', submit_page_path)}
  %li #{link_to('Friends & Bastards', friends_and_bastards_path)}

app/views/layouts/admin.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Jerry Magazine</title>
  
  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister|Cabin+Sketch:700&v2' %>
  <%= stylesheet_link_tag "/assets/admin" %>
  <%= javascript_include_tag "/assets/admin" %>
  <%= csrf_meta_tag %>
  
  <%= include_tiny_mce_if_needed %>
  
</head>
<body>
<div id="wrapper" class="container_12">
  <h1 class="grid_4">Jerry Admin</h1>
  <div id="main_menu" class="grid_8">
    <ul>
      <li><%= link_to 'admin home', :controller => 'admin' %></li>
      <li><%= link_to 'users', :controller => 'users' %></li>
      <li><%= link_to 'editions', editions_admin_path %></li>
      <li><%= link_to 'works', works_admin_path %></li>
      <li><%= link_to 'links', links_admin_path %></li>
      <li><%= link_to 'site home', '/' %></li>
    </ul>
  </div>
  <p class="grid_12" id="flash_message"><%= flash[:notice] %></p>

  <div class="grid_12">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title JERRY MAGAZINE
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Lato:400,400italic,700,700italic"
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Syncopate:400,700"
    = stylesheet_link_tag "/assets/application"
    = javascript_include_tag "/assets/application"
    = csrf_meta_tag
  %body
    #wrapper.container_12
      #fixed_furniture.grid_5.prefix_1
        %a#main_image.grid_5{:href => "/home"}
        %h1.grid_5
          %a{:href => "/home"}
            %span> J
            erry
        .clear
        = render 'layouts/main_mav'
      #main.grid_6
        %h1= @edition.title
        = yield
      #footer.grid_12
        = render 'layouts/footer'
    = render 'layouts/google_analytics'

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>JERRY MAGAZINE</title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <%= stylesheet_link_tag "application-edition-#{@edition.edition_no}" %>
  </head>
  <body>
    <div id="wrapper">
      <div id="header">
        <%= link_to(image_tag("jerry_logo-edition-#{@edition.edition_no}.png"), home_path, :id => "main_logo") %>
      </div>
      <div id="main_nav">
        <ul>
          <li><%=link_to('home', home_path) %></li>
          <li><%=link_to('about us', about_us_path) %></li>
          <li><%=link_to('archives', archives_path) %></li>
          <li><%=link_to('submit', submit_page_path) %></li>
          <li><%=link_to('links', links_path) %></li>
        </ul>
      </div>
      <br clear="both"/>
      <div id="main">
        <%= yield %>
      </div>
      <br clear="both"/>
      <div id="footer">
        <div>made by <a href="http://www.fluxequalsrad.com">Flux=Rad</a></div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application_old.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>JERRY MAGAZINE</title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <%= stylesheet_link_tag "application-edition-#{@edition.edition_no}" %>
  </head>
  <body>
    <div id="wrapper">
      <div id="header">
        <%= link_to(image_tag("jerry_logo-edition-#{@edition.edition_no}.png"), home_path, :id => "main_logo") %>
      </div>
      <div id="main_nav">
        <ul>
          <li><%=link_to('home', home_path) %></li>
          <li><%=link_to('about us', about_us_path) %></li>
          <li><%=link_to('archives', archives_path) %></li>
          <li><%=link_to('submit', submit_page_path) %></li>
          <li><%=link_to('links', links_path) %></li>
        </ul>
      </div>
      <br clear="both"/>
      <div id="main">
        <%= yield %>
      </div>
      <br clear="both"/>
      <div id="footer">
        <div>made by <a href="http://www.fluxequalsrad.com">Flux=Rad</a></div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/front_cover.haml
!!! 5
%html
  %head
    %title JERRY MAGAZINE
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Syncopate:400,700"
    = stylesheet_link_tag "/assets/front-cover"
  %body{:id => "edition-#{@edition.edition_no}"}
    #wrapper.container_12
      = render "public/front_cover_#{@edition.edition_no}"
      
    = render 'layouts/google_analytics'

app/views/layouts/work.haml
!!! 5
%html
  %head
    %title JERRY MAGAZINE
    = stylesheet_link_tag "/assets/colaborate-type.css"
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Syncopate:400,700"
    = stylesheet_link_tag "/assets/application"
    = javascript_include_tag "/assets/application"
    = csrf_meta_tag
  %body
    #work_wrapper.container_12
      #fixed_furniture.grid_3
        %a#main_image.grid_3{:href => "/home"}
        %h1.grid_3
          %a{:href => "/home"}
            %span> J
            erry
        .clear
        = render 'layouts/main_mav'
      #main.grid_9
        %h1= @edition.title
        = yield
      #footer.grid_12
        = render 'layouts/footer'
    = render 'layouts/google_analytics'